spring.application.name=vuln-crawler

# Server
server.port=8089

# DataSource
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/test_spring?autoReconnect=true&useUnicode=true&characterEncoding=utf8
#spring.datasource.url=jdbc:postgresql://localhost:5432/test_spring?autoReconnect=true&useUnicode=true&characterEncoding=utf8&stringtype=unspecified
#spring.datasource.url=jdbc:postgresql://localhost:5432/test_spring?currentSchema=test_schema&autoReconnect=true&useUnicode=true&characterEncoding=utf8&stringtype=unspecified
spring.datasource.url=jdbc:postgresql://localhost:5432/test_spring?currentSchema=test_schema&ssl=false&characterEncoding=UTF-8&stringtype=unspecified
spring.datasource.username=test
spring.datasource.password=1234

# HikariCP
spring.datasource.hikari.pool-name=hikari-cp
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.data-source-properties.cachePrepStmts=true
spring.datasource.hikari.data-source-properties.prepStmtCacheSize=250
spring.datasource.hikari.data-source-properties.prepStmtCacheSqlLimit=2048
spring.datasource.hikari.data-source-properties.useServerPrepStmts=true

# Batch Table Initialize
spring.batch.jdbc.initialize-schema=always

#logging.level.com.osckorea.vuln_crawler=DEBUG
